# docker-compose version
version: '3.3'

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../:/var/www/
      - ./logs/nginx:/var/log/nginx/
    #  - ./Nginx/html:/usr/share/nginx/html/
    links:
      - php


  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    container_name: mysql
    # there must be your real names and passwords
    environment:
      - MYSQL_ROOT_PASSWORD=yourrootpassword
      - MYSQL_DATABASE=yourdatabase
      - MYSQL_USER=youruser
      - MYSQL_PASSWORD=yourpassword

    volumes:
      - ./mysql/data:/var/lib/mysql

  #redis:
  #  image: redis:5.0.6
  #  ports:
  #    - "6379:6379"
  #  container_name: redis
  #  volumes:
  #    - ./redis/data:/data

  #nats:
  #  image: nats
  #  ports:
  #    - "4222:4222"
  #    - "6222:6222"
  #    - "8222:8222"
  #  container_name: nats

  centrifugo:
    image: centrifugo/centrifugo
    ports:
      - "8000:8000"
    container_name: centrifugo
    ulimits:
      nofile: 65536
    volumes:
      - ./centrifugo/config_json:/centrifugo
    command: centrifugo -c config.json --admin --admin_insecure

  php:
    # custom Dockerfile directory
    build: ./php
    container_name: php-fpm
    ports:
      - "2346:2346"
      - "9000:9000"
      - "9501:9501"
    volumes:
      - ../:/var/www
    links:
      - mysql
      #- redis
      #- nats
